package analyzer

import (
	"encoding/json"
	"strings"
	"testing"

	"github.com/fernando143/patro/internal/domain/meeting"
)

// The expected prompts below were generated by running the reference
// Python implementation (scribe/analyzer.py's build_prompt) with the same
// arguments; BuildPrompt must reproduce them byte-for-byte.

const expectedPromptFull = `You are analyzing a meeting transcript to distill it into a personal knowledge library.

First, read the meeting transcript from this file using your file reading tool: /tmp/proj/.state/tmp/transcript-abc123.txt
Base your entire analysis on its contents.

The knowledge library already contains these topics (slug: name):
- go-migration: Go Migration
- obs-setup: OBS Setup
REUSE an existing slug whenever the subject of a topic matches. Only create a new slug for genuinely new subjects.

Respond with ONLY a valid JSON object (no prose, no markdown fences) matching exactly this schema:
{
  "meeting": {
    "title": "short descriptive title",
    "summary": "2-4 sentence summary of the meeting",
    "key_points": ["point 1", "point 2"],
    "decisions": ["decision 1"],
    "action_items": [{"owner": "person name or 'unassigned'", "task": "what must be done"}]
  },
  "topics": [
    {
      "slug": "kebab-case-slug",
      "name": "Human readable name",
      "content": "Markdown with what was newly learned about this topic in this meeting"
    }
  ]
}

Rules:
- Slugs must be lowercase kebab-case, ASCII, no accents.
- "content" of each topic is Markdown: what was newly learned about that topic in THIS meeting (facts, decisions, context), not a meeting summary.
- 1 to 5 topics, each focused on a single subject.
- Write ALL output (title, summary, key points, decisions, action items, topic names and content) in the same language as the transcript ("en").
- If a list would be empty, use an empty array.
- Your final message must contain ONLY the JSON object, nothing else.
`

const expectedPromptEmptyUnknown = `You are analyzing a meeting transcript to distill it into a personal knowledge library.

Analyze the meeting transcript provided with this request.

The knowledge library is empty yet. Create slugs for every subject discussed.

Respond with ONLY a valid JSON object (no prose, no markdown fences) matching exactly this schema:
{
  "meeting": {
    "title": "short descriptive title",
    "summary": "2-4 sentence summary of the meeting",
    "key_points": ["point 1", "point 2"],
    "decisions": ["decision 1"],
    "action_items": [{"owner": "person name or 'unassigned'", "task": "what must be done"}]
  },
  "topics": [
    {
      "slug": "kebab-case-slug",
      "name": "Human readable name",
      "content": "Markdown with what was newly learned about this topic in this meeting"
    }
  ]
}

Rules:
- Slugs must be lowercase kebab-case, ASCII, no accents.
- "content" of each topic is Markdown: what was newly learned about that topic in THIS meeting (facts, decisions, context), not a meeting summary.
- 1 to 5 topics, each focused on a single subject.
- Write ALL output (title, summary, key points, decisions, action items, topic names and content) in the same language the transcript is written in.
- If a list would be empty, use an empty array.
- Your final message must contain ONLY the JSON object, nothing else.
`

const expectedPromptTopicsNoPathPt = `You are analyzing a meeting transcript to distill it into a personal knowledge library.

Analyze the meeting transcript provided with this request.

The knowledge library already contains these topics (slug: name):
- produto: Produto
REUSE an existing slug whenever the subject of a topic matches. Only create a new slug for genuinely new subjects.

Respond with ONLY a valid JSON object (no prose, no markdown fences) matching exactly this schema:
{
  "meeting": {
    "title": "short descriptive title",
    "summary": "2-4 sentence summary of the meeting",
    "key_points": ["point 1", "point 2"],
    "decisions": ["decision 1"],
    "action_items": [{"owner": "person name or 'unassigned'", "task": "what must be done"}]
  },
  "topics": [
    {
      "slug": "kebab-case-slug",
      "name": "Human readable name",
      "content": "Markdown with what was newly learned about this topic in this meeting"
    }
  ]
}

Rules:
- Slugs must be lowercase kebab-case, ASCII, no accents.
- "content" of each topic is Markdown: what was newly learned about that topic in THIS meeting (facts, decisions, context), not a meeting summary.
- 1 to 5 topics, each focused on a single subject.
- Write ALL output (title, summary, key points, decisions, action items, topic names and content) in the same language as the transcript ("pt").
- If a list would be empty, use an empty array.
- Your final message must contain ONLY the JSON object, nothing else.
`

func TestBuildPromptFull(t *testing.T) {
	got := BuildPrompt(
		[]meeting.TopicRef{
			{Slug: "go-migration", Name: "Go Migration"},
			{Slug: "obs-setup", Name: "OBS Setup"},
		},
		"en",
		"/tmp/proj/.state/tmp/transcript-abc123.txt",
	)
	if got != expectedPromptFull {
		t.Errorf("BuildPrompt mismatch:\n--- got ---\n%q\n--- want ---\n%q", got, expectedPromptFull)
	}
}

func TestBuildPromptEmptyLibraryUnknownLanguage(t *testing.T) {
	got := BuildPrompt(nil, "unknown", "")
	if got != expectedPromptEmptyUnknown {
		t.Errorf("BuildPrompt mismatch:\n--- got ---\n%q\n--- want ---\n%q", got, expectedPromptEmptyUnknown)
	}
}

func TestBuildPromptExistingTopicsNoPath(t *testing.T) {
	got := BuildPrompt([]meeting.TopicRef{{Slug: "produto", Name: "Produto"}}, "pt", "")
	if got != expectedPromptTopicsNoPathPt {
		t.Errorf("BuildPrompt mismatch:\n--- got ---\n%q\n--- want ---\n%q", got, expectedPromptTopicsNoPathPt)
	}
}

func TestBuildPromptKeyBlocks(t *testing.T) {
	withTopics := BuildPrompt([]meeting.TopicRef{{Slug: "a", Name: "A"}}, "en", "/tmp/t.txt")
	for _, block := range []string{
		"First, read the meeting transcript from this file using your file reading tool: /tmp/t.txt\n" +
			"Base your entire analysis on its contents.",
		"The knowledge library already contains these topics (slug: name):\n- a: A\n",
		"REUSE an existing slug whenever the subject of a topic matches.",
		`in the same language as the transcript ("en").`,
	} {
		if !strings.Contains(withTopics, block) {
			t.Errorf("prompt with topics missing block %q", block)
		}
	}
	if strings.Contains(withTopics, "The knowledge library is empty yet.") {
		t.Error("prompt with topics must not contain the empty-library block")
	}

	empty := BuildPrompt(nil, "", "")
	for _, block := range []string{
		"Analyze the meeting transcript provided with this request.",
		"The knowledge library is empty yet. Create slugs for every subject discussed.",
		"in the same language the transcript is written in.",
	} {
		if !strings.Contains(empty, block) {
			t.Errorf("empty-library prompt missing block %q", block)
		}
	}
	if strings.Contains(empty, "REUSE an existing slug") {
		t.Error("empty-library prompt must not contain the reuse block")
	}

	// "" and "unknown" languages produce the same rule.
	if BuildPrompt(nil, "", "") != BuildPrompt(nil, "unknown", "") {
		t.Error(`language "" and "unknown" should produce identical prompts`)
	}
}

func TestParseAnalysisCleanJSON(t *testing.T) {
	raw := `{
	  "meeting": {
	    "title": "Go migration kickoff",
	    "summary": "The team planned the Go port.",
	    "key_points": ["port analyzer first", "keep JSON contract"],
	    "decisions": ["use AssemblyAI SDK"],
	    "action_items": [{"owner": "Ana", "task": "write tests"}]
	  },
	  "topics": [
	    {"slug": "go-migration", "name": "Go Migration", "content": "Port started."}
	  ]
	}`
	got := ParseAnalysis(raw, "Test")
	if got.Title != "Go migration kickoff" {
		t.Errorf("Title = %q", got.Title)
	}
	if got.Summary != "The team planned the Go port." {
		t.Errorf("Summary = %q", got.Summary)
	}
	if len(got.KeyPoints) != 2 || got.KeyPoints[0] != "port analyzer first" || got.KeyPoints[1] != "keep JSON contract" {
		t.Errorf("KeyPoints = %v", got.KeyPoints)
	}
	if len(got.Decisions) != 1 || got.Decisions[0] != "use AssemblyAI SDK" {
		t.Errorf("Decisions = %v", got.Decisions)
	}
	if len(got.ActionItems) != 1 || got.ActionItems[0] != (meeting.ActionItem{Owner: "Ana", Task: "write tests"}) {
		t.Errorf("ActionItems = %v", got.ActionItems)
	}
	if len(got.Topics) != 1 || got.Topics[0] != (meeting.Topic{Slug: "go-migration", Name: "Go Migration", Content: "Port started."}) {
		t.Errorf("Topics = %v", got.Topics)
	}
}

func TestParseAnalysisFencedJSON(t *testing.T) {
	body := `{"meeting": {"title": "Fenced", "summary": "s"}, "topics": []}`
	for _, raw := range []string{
		"```json\n" + body + "\n```",
		"```\n" + body + "\n```",
		"  ```json  " + body + " ```  ",
	} {
		got := ParseAnalysis(raw, "Test")
		if got.Title != "Fenced" {
			t.Errorf("ParseAnalysis(%q).Title = %q, want %q", raw, got.Title, "Fenced")
		}
	}
}

func TestParseAnalysisProseWrappedJSON(t *testing.T) {
	raw := `Here is the analysis you asked for:

{"meeting": {"title": "Prose", "summary": "wrapped"}, "topics": [{"slug": "x"}]}

Hope this helps!`
	got := ParseAnalysis(raw, "Test")
	if got.Title != "Prose" {
		t.Errorf("Title = %q, want %q", got.Title, "Prose")
	}
	if got.Summary != "wrapped" {
		t.Errorf("Summary = %q, want %q", got.Summary, "wrapped")
	}
	if len(got.Topics) != 1 || got.Topics[0].Slug != "x" {
		t.Errorf("Topics = %v", got.Topics)
	}
}

func TestParseAnalysisMissingMeetingFallback(t *testing.T) {
	raw := `{"topics": [{"slug": "x", "content": "y"}]}`
	got := ParseAnalysis(raw, "Test")
	wantSummary := strings.TrimSpace(raw)
	if got.Title != "Untitled meeting" {
		t.Errorf("Title = %q, want %q", got.Title, "Untitled meeting")
	}
	if got.Summary != wantSummary {
		t.Errorf("Summary = %q, want %q", got.Summary, wantSummary)
	}
	if len(got.Topics) != 1 ||
		got.Topics[0] != (meeting.Topic{Slug: "general", Name: "General", Content: wantSummary}) {
		t.Errorf("Topics = %v", got.Topics)
	}
}

func TestParseAnalysisGarbageFallback(t *testing.T) {
	got := ParseAnalysis("this is not JSON at all", "Test")
	if got.Title != "Untitled meeting" {
		t.Errorf("Title = %q", got.Title)
	}
	if got.Summary != "this is not JSON at all" {
		t.Errorf("Summary = %q", got.Summary)
	}
	if len(got.Topics) != 1 || got.Topics[0].Slug != "general" || got.Topics[0].Name != "General" ||
		got.Topics[0].Content != got.Summary {
		t.Errorf("Topics = %v", got.Topics)
	}
}

func TestParseAnalysisEmptyFallback(t *testing.T) {
	got := ParseAnalysis("   \n  ", "Test")
	want := "Analysis failed to produce a parseable result."
	if got.Summary != want {
		t.Errorf("Summary = %q, want %q", got.Summary, want)
	}
	if len(got.Topics) != 1 || got.Topics[0].Content != want {
		t.Errorf("Topics = %v", got.Topics)
	}
}

func TestParseAnalysisFallbackTruncatesTo2000Runes(t *testing.T) {
	raw := strings.Repeat("é", 2500) // multi-byte: rune count is what matters
	got := ParseAnalysis(raw, "Test")
	if n := len([]rune(got.Summary)); n != 2000 {
		t.Errorf("len(Summary) = %d runes, want 2000", n)
	}
}

func TestParseAnalysisStringActionItems(t *testing.T) {
	raw := `{"meeting": {
	  "title": "t",
	  "summary": "s",
	  "action_items": [
	    "review the PR",
	    {"owner": "Bob", "task": "deploy"},
	    {"task": "no owner given"},
	    {"owner": null, "task": "null owner"},
	    "",
	    0
	  ]
	}}`
	got := ParseAnalysis(raw, "Test")
	want := []meeting.ActionItem{
		{Owner: "unassigned", Task: "review the PR"},
		{Owner: "Bob", Task: "deploy"},
		{Owner: "unassigned", Task: "no owner given"},
		{Owner: "None", Task: "null owner"}, // Python str(None)
	}
	if len(got.ActionItems) != len(want) {
		t.Fatalf("ActionItems = %v, want %v", got.ActionItems, want)
	}
	for i, item := range want {
		if got.ActionItems[i] != item {
			t.Errorf("ActionItems[%d] = %v, want %v", i, got.ActionItems[i], item)
		}
	}
}

func TestParseAnalysisTopicDefaults(t *testing.T) {
	raw := `{"meeting": {"title": "t", "summary": "s"}, "topics": [
	  {"slug": "only-slug"},
	  {"slug": "full", "name": "Full Name", "content": "content here"},
	  {"name": "no slug", "content": "skipped"},
	  {"slug": ""},
	  "not an object",
	  {"slug": "null-name", "name": null, "content": null}
	]}`
	got := ParseAnalysis(raw, "Test")
	want := []meeting.Topic{
		{Slug: "only-slug", Name: "only-slug", Content: ""},
		{Slug: "full", Name: "Full Name", Content: "content here"},
		{Slug: "null-name", Name: "null-name", Content: ""},
	}
	if len(got.Topics) != len(want) {
		t.Fatalf("Topics = %v, want %v", got.Topics, want)
	}
	for i, topic := range want {
		if got.Topics[i] != topic {
			t.Errorf("Topics[%d] = %v, want %v", i, got.Topics[i], topic)
		}
	}
}

func TestParseAnalysisTitleAndListDefaults(t *testing.T) {
	// Missing title defaults; non-list key_points/decisions are ignored.
	raw := `{"meeting": {"summary": "s", "key_points": "not a list", "decisions": 42}}`
	got := ParseAnalysis(raw, "Test")
	if got.Title != "Untitled meeting" {
		t.Errorf("Title = %q, want %q", got.Title, "Untitled meeting")
	}
	if len(got.KeyPoints) != 0 {
		t.Errorf("KeyPoints = %v, want empty", got.KeyPoints)
	}
	if len(got.Decisions) != 0 {
		t.Errorf("Decisions = %v, want empty", got.Decisions)
	}

	// Empty title also falls back to the default.
	raw = `{"meeting": {"title": "", "summary": "s"}, "topics": []}`
	if got := ParseAnalysis(raw, "Test"); got.Title != "Untitled meeting" {
		t.Errorf("Title = %q, want %q", got.Title, "Untitled meeting")
	}
}

func TestIsTruthy(t *testing.T) {
	tests := []struct {
		name  string
		value any
		want  bool
	}{
		{"nil", nil, false},
		{"true", true, true},
		{"false", false, false},
		{"non-empty string", "x", true},
		{"empty string", "", false},
		{"non-zero float", float64(1), true},
		{"zero float", float64(0), false},
		{"non-empty slice", []any{1}, true},
		{"empty slice", []any{}, false},
		{"non-empty map", map[string]any{"a": 1}, true},
		{"empty map", map[string]any{}, false},
		{"unrecognized type defaults true", struct{}{}, true},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := isTruthy(tt.value); got != tt.want {
				t.Errorf("isTruthy(%#v) = %v, want %v", tt.value, got, tt.want)
			}
		})
	}
}

func TestPyStr(t *testing.T) {
	tests := []struct {
		name  string
		value any
		want  string
	}{
		{"nil", nil, "None"},
		{"string", "hello", "hello"},
		{"true", true, "True"},
		{"false", false, "False"},
		{"float", float64(3.5), "3.5"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := pyStr(tt.value); got != tt.want {
				t.Errorf("pyStr(%#v) = %q, want %q", tt.value, got, tt.want)
			}
		})
	}
}

// TestResponseSchemaMatchesParser is the build-time contract check: it
// fails if internal/adapter/analyzer/response_schema.json (authored in Langfuse,
// synced by tools/promptsync) drifts from the exact keys parseResponse
// reads. parseResponse degrades gracefully on missing keys instead of
// erroring, so a schema edit that renames or drops a field would otherwise
// only surface as silently empty output at runtime — this test is what
// turns that into a build failure instead.
func TestResponseSchemaMatchesParser(t *testing.T) {
	var schema map[string]any
	if err := json.Unmarshal([]byte(responseSchema), &schema); err != nil {
		t.Fatalf("response_schema.json is not valid JSON: %v", err)
	}

	meeting, ok := schema["meeting"].(map[string]any)
	if !ok {
		t.Fatal(`schema is missing a "meeting" object — parseResponse reads payload["meeting"]`)
	}
	for _, key := range []string{"title", "summary", "key_points", "decisions", "action_items"} {
		if _, ok := meeting[key]; !ok {
			t.Errorf("schema.meeting is missing %q — parseResponse reads meeting[%q]", key, key)
		}
	}

	actionItems, ok := meeting["action_items"].([]any)
	if !ok || len(actionItems) == 0 {
		t.Fatal("schema.meeting.action_items must be a non-empty example array")
	}
	actionItem, ok := actionItems[0].(map[string]any)
	if !ok {
		t.Fatal("schema.meeting.action_items[0] must be an object")
	}
	for _, key := range []string{"owner", "task"} {
		if _, ok := actionItem[key]; !ok {
			t.Errorf("schema.meeting.action_items[0] is missing %q — parseResponse reads it", key)
		}
	}

	topics, ok := schema["topics"].([]any)
	if !ok || len(topics) == 0 {
		t.Fatal(`schema is missing a non-empty "topics" example array — parseResponse reads payload["topics"]`)
	}
	topic, ok := topics[0].(map[string]any)
	if !ok {
		t.Fatal("schema.topics[0] must be an object")
	}
	for _, key := range []string{"slug", "name", "content"} {
		if _, ok := topic[key]; !ok {
			t.Errorf("schema.topics[0] is missing %q — parseResponse reads it", key)
		}
	}
}

// TestPromptFragmentsRetainPlaceholders guards the same failure mode as
// TestResponseSchemaMatchesParser but for the conditional fragments: since
// strings.Replace silently no-ops when its old string isn't found, an
// Langfuse edit that drops {{transcript_path}} (or similar) would silently
// omit real data from the prompt instead of failing anywhere.
func TestPromptFragmentsRetainPlaceholders(t *testing.T) {
	tests := []struct {
		name        string
		fragment    string
		placeholder string
	}{
		{"topics_with_existing.txt", topicsWithExistingFragment, "{{topics_list}}"},
		{"source_with_path.txt", sourceWithPathFragment, "{{transcript_path}}"},
		{"language_known.txt", languageKnownFragment, "{{language}}"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if !strings.Contains(tt.fragment, tt.placeholder) {
				t.Errorf("%s is missing placeholder %q — BuildPrompt substitutes real data there", tt.name, tt.placeholder)
			}
		})
	}
}
