# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Patro < Formula
  desc "Watch an OBS recordings folder, transcribe meetings with AssemblyAI and distill them into a Markdown knowledge library"
  homepage "https://github.com/fernando143/patro"
  version "0.3.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fernando143/patro/releases/download/v0.3.2/patro_0.3.2_darwin_amd64.tar.gz"
      sha256 "a8ec17a996760588cbdb6b90c88ebdbfeb555a2f279f8c9e760623630f928656"

      define_method(:install) do
        bin.install "patro"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fernando143/patro/releases/download/v0.3.2/patro_0.3.2_darwin_arm64.tar.gz"
      sha256 "285f3e2aaf027d1d567ac010b05cc7be4614fd483e1305908da15d15e7b84f00"

      define_method(:install) do
        bin.install "patro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fernando143/patro/releases/download/v0.3.2/patro_0.3.2_linux_amd64.tar.gz"
      sha256 "f0ff8e1bfb0f5cd55cddbfe9e76d2bd1ea165dce62862ce1f12d8cdf01155151"
      define_method(:install) do
        bin.install "patro"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fernando143/patro/releases/download/v0.3.2/patro_0.3.2_linux_arm64.tar.gz"
      sha256 "c6ba1e0b0c2de6b490bf2aa8aaacb82e128883611312f16270a523cb42a7ba93"
      define_method(:install) do
        bin.install "patro"
      end
    end
  end

  def caveats
    <<~EOS
      To get started:
        1. Run `patro init` to create the config at ~/.config/patro/config.yaml
        2. Set your AssemblyAI API key: export ASSEMBLYAI_API_KEY=<your-key>
        3. Optionally run the watcher in the background: brew services start patro
    EOS
  end

  service do
    run [opt_bin/"patro", "serve"]
    keep_alive true
    log_path var/"log/patro.log"
    error_log_path var/"log/patro.log"
  end
end
