# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Patro < Formula
  desc "Watch an OBS recordings folder, transcribe meetings with AssemblyAI and distill them into a Markdown knowledge library"
  homepage "https://github.com/fernando143/patro"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fernando143/patro/releases/download/v0.3.0/patro_0.3.0_darwin_amd64.tar.gz"
      sha256 "4c111136997fe79cd7975d87a2891e17233619fda9d762514d01fb3792431e40"

      define_method(:install) do
        bin.install "patro"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fernando143/patro/releases/download/v0.3.0/patro_0.3.0_darwin_arm64.tar.gz"
      sha256 "b4edbe02a259d2c09b9b715dd6a98f53b76f11f6c9730bbb8d33ba110e404f98"

      define_method(:install) do
        bin.install "patro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fernando143/patro/releases/download/v0.3.0/patro_0.3.0_linux_amd64.tar.gz"
      sha256 "8fcc518d888e9319f55b8956143371a0f84fa97de61d449fb5575ce2660338ea"
      define_method(:install) do
        bin.install "patro"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fernando143/patro/releases/download/v0.3.0/patro_0.3.0_linux_arm64.tar.gz"
      sha256 "1e9ec74dd3bdbc60064b40057df751d0f50e79f6283c28baf69b9fc4c37fb916"
      define_method(:install) do
        bin.install "patro"
      end
    end
  end

  def caveats
    <<~EOS
      To get started:
        1. Run `patro init` to create the config at ~/.config/patro/config.yaml
        2. Set your AssemblyAI API key: export ASSEMBLYAI_API_KEY=<your-key>
        3. Optionally run the watcher in the background: brew services start patro
    EOS
  end

  service do
    run [opt_bin/"patro", "serve"]
    keep_alive true
    log_path var/"log/patro.log"
    error_log_path var/"log/patro.log"
  end
end
