# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Patro < Formula
  desc "Watch an OBS recordings folder, transcribe meetings with AssemblyAI and distill them into a Markdown knowledge library"
  homepage "https://github.com/fernando143/patro"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fernando143/patro/releases/download/v0.6.0/patro_0.6.0_darwin_amd64.tar.gz"
      sha256 "4f7fa1f0725f243ac8da3940f09837ffb52f088d45cb53a306d86554d6032b11"

      define_method(:install) do
        bin.install "patro"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fernando143/patro/releases/download/v0.6.0/patro_0.6.0_darwin_arm64.tar.gz"
      sha256 "31476204f125e29f15984bec20a458efc050ff1fe69e00df01d717f06f701609"

      define_method(:install) do
        bin.install "patro"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fernando143/patro/releases/download/v0.6.0/patro_0.6.0_linux_amd64.tar.gz"
      sha256 "ec3cc6d30dcc07ec2bcb394f8b7e470d9358bb94f580cd74e0fe3942a932a7dd"
      define_method(:install) do
        bin.install "patro"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fernando143/patro/releases/download/v0.6.0/patro_0.6.0_linux_arm64.tar.gz"
      sha256 "d8994d9e7ab1677d64ddff5e0f5d390b78746fa5a79d4714ec3aeb327bf8ed79"
      define_method(:install) do
        bin.install "patro"
      end
    end
  end

  def caveats
    <<~EOS
      To get started:
        1. Run `patro init` to create the config at ~/.config/patro/config.yaml
        2. Set your AssemblyAI API key: export ASSEMBLYAI_API_KEY=<your-key>
        3. Optionally run the watcher in the background: brew services start patro
    EOS
  end

  service do
    run [opt_bin/"patro", "serve"]
    keep_alive true
    log_path var/"log/patro.log"
    error_log_path var/"log/patro.log"
  end
end
