#!/usr/bin/env bash
# Run the project's quality checks and write a report even when a check fails.
set -u -o pipefail

report_dir="${QUALITY_REPORT_DIR:-artifacts/quality}"
report_path="${report_dir}/report.md"
temp_dir="$(mktemp -d)"
blocking_failures=0

cleanup() {
  rm -rf "${temp_dir}"
}
trap cleanup EXIT

mkdir -p "${report_dir}"

{
  printf '# Quality report\n\n'
  printf 'Generated: `%s`\n\n' "$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  printf 'This report is generated by `scripts/quality-report.sh`. `go vet`, tests, Staticcheck, and GolangCI-Lint are quality gates; complexity and duplication findings are informational.\n\n'
  printf '## Environment\n\n```text\n'
  go version 2>&1 || true
  git rev-parse --short HEAD 2>&1 || true
  printf '```\n\n'
} >"${report_path}"

run_check() {
  local name="$1"
  local command_description="$2"
  local blocking="$3"
  shift 3

  local output_name
  local output_path
  output_name="$(printf '%s' "${name}" | tr ' ' '-')"
  output_path="${temp_dir}/${output_name}"
  local status

  if "$@" >"${output_path}" 2>&1; then
    status=0
  else
    status=$?
  fi

  {
    printf '## %s\n\n' "${name}"
    printf '**Command:** `%s`  \n' "${command_description}"
    if [[ "${status}" -eq 0 ]]; then
      printf '**Status:** passed\n\n'
    else
      printf '**Status:** failed (exit code %s)\n\n' "${status}"
    fi
    printf '```text\n'
    cat "${output_path}"
    printf '\n```\n\n'
  } >>"${report_path}"

  if [[ "${blocking}" == "blocking" && "${status}" -ne 0 ]]; then
    blocking_failures=1
  fi
}

run_check 'Go vet' 'go vet ./...' blocking go vet ./...
run_check 'Go tests' 'go test ./...' blocking go test ./...
run_check 'Staticcheck' 'staticcheck ./...' blocking staticcheck ./...
run_check 'GolangCI-Lint' 'golangci-lint run ./...' blocking golangci-lint run ./...
run_check 'Cyclomatic complexity' 'gocyclo -top 20 .' informational gocyclo -top 20 .
run_check 'Duplicate code' 'dupl -t 100 .' informational dupl -t 100 .

if [[ "${blocking_failures}" -ne 0 ]]; then
  printf 'Quality gates failed; see %s.\n' "${report_path}" >&2
  exit 1
fi

printf 'Quality report written to %s.\n' "${report_path}"
